importfile: goods.json
rootpassword:
spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  security:
    basic:
      enabled: true
  data:
    rest:
      basePath: /api
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
  headers:
    Authorization:
jwt:
  secret: